apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: ws-module-aws-waf-hashibank
spec:
  name: ws-module-aws-waf-hashibank
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  description: Workspace created using k8s operator
  applyMethod: auto
  executionMode: remote
  terraformVariables:
    - name: region
      hcl: false
      value: "ap-southeast-2"
    - name: web_acl_name
      hcl: false
      value: "app_hashibank_nouseragent"
---
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: module-aws-waf-hashibank
spec:
  name: module-aws-waf-hashibank
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  module:
    source: github.com/hashi-demo-lab/tfc-operator-k8s//terraform-aws-wafv2-webacl
  variables:
    - name: region
    - name: web_acl_name
  outputs:
    - name: waf_arn
    - name: waf_capacity
    - name: waf_id
    - name: waf_tags_all
  workspace:
    name: ws-module-aws-waf-hashibank