apiVersion: batch/v1
kind: Job
metadata:
  name: poll-configmap-hashibank
spec:
  backoffLimit: 30
  template:
    spec:
      serviceAccountName: ingress-patcher-sa # this needs to be created see role folder
      containers:
        - name: main-container
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              if [ -z "$WAF_ARN" ]; then
                echo "Environment variable WAF_ARN is not set!"
                # Handle the error or exit
                exit 1
              else
                # Getting WAF Arn for app ALB ingress - WAF ACL created by Terraform
                echo "WAF_ARN is set with value: $WAF_ARN"
                kubectl annotate ingress hashibank alb.ingress.kubernetes.io/wafv2-acl-arn=$WAF_ARN --overwrite
              fi
          env:
            - name: WAF_ARN
              valueFrom:
                configMapKeyRef:
                  name: ws-module-aws-waf-hashibank-outputs
                  key: waf_arn
      restartPolicy: Never
