apiVersion: batch/v1
kind: Job
metadata:
  name: poll-configmap-hashibank
spec:
  backoffLimit: 30
  template:
    spec:
      initContainers:
        - name: check-configmap
          image: bitnami/kubectl:latest
          command: ["kubectl", "get", "configmap", "ws-module-aws-waf-hashibank-outputs"]
      containers:
        - name: main-container
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              if [ -z "$WAF_ARN" ]; then
                echo "Environment variable WAF_ARN is not set!"
                # Handle the error or exit
                exit 1
              else
                # Your main logic here
                echo "WAF_ARN is set with value: $WAF_ARN"
                kubectl -n app-hashibank patch ingress hashibank --type=json -p "[{\"op\": \"replace\", \"path\": \"/metadata/annotations/alb.ingress.kubernetes.io~1wafv2-acl-arn\", \"value\": \"$WAF_ARN\"}]"
              fi
          env:
            - name: WAF_ARN
              valueFrom:
                configMapKeyRef:
                  name: ws-module-aws-waf-hashibank-outputs
                  key: waf_arn
      restartPolicy: Never
