apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: crd-workspace-hashibank-aws_waf
spec:
  name: crd-workspace-hashibank-aws_waf
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  description: Workspace created using k8s operator
  applyMethod: auto
  executionMode: remote
  terraformVariables:
    - name: region
      hcl: false
      value: "ap-southeast-2"
    - name: web_acl_name
      hcl: false
      value: "app_hashibank_nouseragent"