apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: module-eks-addon
spec:
  name: module-eks-addon
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  module:
    source: github.com/hashi-demo-lab/tfc-operator-k8s//terraform-aws-eks-addon
  variables:
    - name: region
    - name: cluster_name
    - name: vpc_id
    - name: cluster_endpoint
    - name: cluster_version
    - name: oidc_provider_arn
    - name: cluster_certificate_authority_data
  outputs:
    - name: aws_load_balancer_controller
  workspace:
    name: ws-module-eks-addon
