apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: platform-vpc-env1
spec:
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  name: platform-vpc-env1
  description: Workspace created using k8s operator
  applyMethod: auto
  executionMode: remote