apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: platform-eks-fargate-env1
spec:
  name: platform-eks-fargate-env1
  organization: hashi-demos-apj # replace with your org name
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  module:
    source: github.com/hashi-demo-lab/tfc-operator-k8s//eks-fargate
  variables:
    - name: namespace
      value: app-hashibank
    - name: cluster_name
      value: eks-demo-consumer
    - name: region
      value: ap-southeast-2
  outputs:
    - name: configure_kubectl
  workspace:
    name: platform-eks-fargate-env1
  
