apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-patcher-role
  namespace: app-hashibank
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]  # Read permissions for ConfigMaps
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "patch"]  # Get and patch permissions for Ingress
