resources:
  - ingress.yaml

configMapGenerator:
- name: temp-waf-arn-config
  envs:
  - environment.env  

replacements:
  - source:
      kind: ConfigMap
      name: temp-waf-arn-config
      fieldPath: data.WAF_ARN_VALUE
    targets:
      - select:
          kind: Ingress
          name: hashibank
        fieldPaths:
          - metadata.annotations.[alb.ingress.kubernetes.io/wafv2-acl-arn]
        options:
          create: true
      


