apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-apply-template
spec:
  entrypoint: apply-terraform
  arguments:
    parameters:
    - name: region
      value: ap-southeast-2
    - name: vpc-name
      value: vpc-eks-cluster
    - name: vpc-cidr
      value: 10.0.0.0/16
  templates:
  - name: apply-terraform
    steps:
    - - name: apply-workspace
        template: kubectl-apply
        arguments:
          parameters:
          - name: yaml-content
            value: |
              apiVersion: app.terraform.io/v1alpha2
              kind: Workspace
              metadata:
                name: ws-module-vpc-eks-cluster
              spec:
                applyMethod: auto
                description: Workspace created using k8s operator
                executionMode: remote
                name: ws-module-vpc-eks-cluster
                organization: hashi-demos-apj
                terraformVariables:
                - hcl: false
                  name: region
                  value: "{{workflow.parameters.region}}"
                - hcl: false
                  name: vpc_name
                  value: "{{workflow.parameters.vpc-name}}"
                - hcl: false
                  name: vpc_cidr
                  value: "{{workflow.parameters.vpc-cidr}}"
                token:
                  secretKeyRef:
                    key: token
                    name: tfc-operator
    - - name: apply-module
        template: kubectl-apply
        arguments:
          parameters:
          - name: yaml-content
            value: |
              apiVersion: app.terraform.io/v1alpha2
              kind: Module
              metadata:
                name: module-vpc-eks-cluster
              spec:
                module:
                  source: github.com/hashi-demo-lab/tfc-operator-k8s//terraform-aws-vpc
                name: module-vpc-eks-cluster
                organization: hashi-demos-apj
                outputs:
                - name: vpc_id
                - name: private_subnets
                token:
                  secretKeyRef:
                    key: token
                    name: tfc-operator
                variables:
                - name: region
                  value: "{{workflow.parameters.region}}"
                - name: vpc_name
                  value: "{{workflow.parameters.vpc-name}}"
                - name: vpc_cidr
                  value: "{{workflow.parameters.vpc-cidr}}"
                workspace:
                  name: ws-module-vpc-eks-cluster
                  
  - name: kubectl-apply
    inputs:
      parameters:
      - name: yaml-content
    container:
      image: bitnami/kubectl:latest
      command: [sh, -c]
      args: ["echo '{{inputs.parameters.yaml-content}}' | kubectl apply -f -"]
