# in a workflow. The resource template type accepts any k8s manifest
# (including CRDs) and can perform any `kubectl` action against it (e.g. create,
# apply, delete, patch).
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: module-vpc-
spec:
  arguments:
    parameters:
    - name: region
      default: "ap-southeast-2"
    - name: vpc-name
      default: "vpc-eks-cluster"
    - name: vpc-cidr
    - name: environment
    - name: team
      default: bu1
    - name: appid
      default: app123
    - name: org
      default: hashi-demos-apj
  templates:
  - name: module-vpc
    resource:                   # indicates that this is a resource template
      action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
      # The successCondition and failureCondition are optional expressions.
      # If failureCondition is true, the step is considered failed.
      # If successCondition is true, the step is considered successful.
      # They use kubernetes label selection syntax and can be applied against any field
      # of the resource (not just labels). Multiple AND conditions can be represented by comma
      # delimited expressions.
      # For more details: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
      successCondition: status.run.status in (applied, planned_and_finished)
      failureCondition: status.run.status in (errored, discarded, canceled)
      manifest: |               #put your kubernetes spec here
        apiVersion: app.terraform.io/v1alpha2
        kind: Module
        metadata:
          name: module-vpc-"{{workflow.parameters.team}}{{workflow.parameters.environment}}{{workflow.parameters.appid}}"
        spec:
          name: module-vpc-"{{workflow.parameters.team}}{{workflow.parameters.environment}}{{workflow.parameters.appid}}"
          organization: hashi-demos-apj # replace with your org name
          token:
            secretKeyRef:
              name: tfc-operator
              key: token
          module:
            source: github.com/hashi-demo-lab/tfc-operator-k8s//terraform-aws-vpc
          variables:
            - name: region
            - name: vpc_name
            - name: vpc_cidr
          outputs:
            - name: vpc_id
            - name: private_subnets
          workspace:
            name: ws-vpc-"{{workflow.parameters.team}}{{workflow.parameters.environment}}{{workflow.parameters.appid}}"